// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bawefjdrmytljlhrxyzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhd2VmamRybXl0bGpsaHJ4eXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzA5NTIsImV4cCI6MjA2NjQ0Njk1Mn0.Xt-CFQyLpvB2YhlRazriPD3E3_8gHf1p14HIM-LGbvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);